# To start enviroment:
#  $ sudo docker-compose -f docker-compose.yaml down -v && sudo docker-compose -f docker-compose.yaml up

# To stop environment:
#  $ sudo docker-compose -f docker-compose.yaml down -v

version: '3.1'

services:

  fastapi_tutorial_db:
    image: postgres:latest
    restart: always
    ports:
      - 65432:5432
    environment:
      NETWORK_ACCESS: internal
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    networks:
      - fastapi-tutorial

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    # ports:
    #   - 8080:80
    environment:
      NETWORK_ACCESS: internal
      VIRTUAL_HOST: pgadmin.webdev.test
      VIRTUAL_PORT: 80 # Not needed as this container listens on port 80 by default
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: ${PGADMIN_DISABLE_POSTFIX}    
    volumes:
      # sudo chown -R 5050:5050 ./volumes/pgadmin/config
      - ./volumes/pgadmin/config:/var/lib/pgadmin
    networks:
      - fastapi-tutorial

  reverseproxy:
    image: jwilder/nginx-proxy:latest
    depends_on:
      - pgadmin
      - fastapi_tutorial_db
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/reverseproxy/certs:/etc/nginx/certs:ro
      - ./volumes/reverseproxy/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
      - ./volumes/reverseproxy/logs:/var/log/nginx:rw
      - ./volumes/reverseproxy/vhost:/ect/nginx/vhost.d:rw 
      - ./volumes/reverseproxy/html:/usr/share/nginx/html:rw 
    networks:
      - fastapi-tutorial

networks:
  fastapi-tutorial: